// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.Descheduler":       schema_pkg_apis_descheduler_v1alpha1_Descheduler(ref),
		"github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.DeschedulerSpec":   schema_pkg_apis_descheduler_v1alpha1_DeschedulerSpec(ref),
		"github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.DeschedulerStatus": schema_pkg_apis_descheduler_v1alpha1_DeschedulerStatus(ref),
		"github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.Param":             schema_pkg_apis_descheduler_v1alpha1_Param(ref),
		"github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.Strategy":          schema_pkg_apis_descheduler_v1alpha1_Strategy(ref),
	}
}

func schema_pkg_apis_descheduler_v1alpha1_Descheduler(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Descheduler is the Schema for the deschedulers API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.DeschedulerSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.DeschedulerStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.DeschedulerSpec", "github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.DeschedulerStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_descheduler_v1alpha1_DeschedulerSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DeschedulerSpec defines the desired state of Descheduler",
				Properties: map[string]spec.Schema{
					"strategies": {
						SchemaProps: spec.SchemaProps{
							Description: "Strategies list of strategies that should be enabled in deschdeular",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.Strategy"),
									},
								},
							},
						},
					},
					"schedule": {
						SchemaProps: spec.SchemaProps{
							Description: "Schedule on which cronjob should run",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"flags": {
						SchemaProps: spec.SchemaProps{
							Description: "Flags for deschedular",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.Param"),
									},
								},
							},
						},
					},
					"image": {
						SchemaProps: spec.SchemaProps{
							Description: "Image of the deschedular being managed, this includes the version",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"flags"},
			},
		},
		Dependencies: []string{
			"github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.Param", "github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.Strategy"},
	}
}

func schema_pkg_apis_descheduler_v1alpha1_DeschedulerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DeschedulerStatus defines the observed state of Descheduler",
				Properties: map[string]spec.Schema{
					"phase": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_descheduler_v1alpha1_Param(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Param is a key/value pair representing the prameter in the stratery or flags",
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"value": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_descheduler_v1alpha1_Strategy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Strategy supported by deschdular",
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"params": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.Param"),
									},
								},
							},
						},
					},
				},
				Required: []string{"params"},
			},
		},
		Dependencies: []string{
			"github.com/skckadiyala/descheduler-operator/pkg/apis/descheduler/v1alpha1.Param"},
	}
}
